name: SoftcoreBan
description: Temporarily ban players when they die and unban them on a specific time
author: JawwadBR
main: com.jawbr.softcoreban.Main
version: 1.3.2
api-version: 1.19

commands:
    softcore-author:
      description: Get plugin Author
      usage: /<command>
      aliases: [scauthor, scbauthor]
  